# Generated by Django 4.2.2 on 2023-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='resident',
            field=models.CharField(max_length=255),
        ),
    ]
